[package]
name = "cat-breeds-k-means"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.7.0"
ndarray = "0.15.6"
rand_distr = "0.4.3"
rand = "0.8.5"
csv = "1.3.0"
